/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MedcareMedicalRecords {
    }
    interface MedcareRemoveAllergyRecords {
    }
    interface MedcareUpdateLabResults {
    }
    interface MedcareVaccinationRecord {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMedcareMedicalRecordsElement extends Components.MedcareMedicalRecords, HTMLStencilElement {
    }
    var HTMLMedcareMedicalRecordsElement: {
        prototype: HTMLMedcareMedicalRecordsElement;
        new (): HTMLMedcareMedicalRecordsElement;
    };
    interface HTMLMedcareRemoveAllergyRecordsElement extends Components.MedcareRemoveAllergyRecords, HTMLStencilElement {
    }
    var HTMLMedcareRemoveAllergyRecordsElement: {
        prototype: HTMLMedcareRemoveAllergyRecordsElement;
        new (): HTMLMedcareRemoveAllergyRecordsElement;
    };
    interface HTMLMedcareUpdateLabResultsElement extends Components.MedcareUpdateLabResults, HTMLStencilElement {
    }
    var HTMLMedcareUpdateLabResultsElement: {
        prototype: HTMLMedcareUpdateLabResultsElement;
        new (): HTMLMedcareUpdateLabResultsElement;
    };
    interface HTMLMedcareVaccinationRecordElement extends Components.MedcareVaccinationRecord, HTMLStencilElement {
    }
    var HTMLMedcareVaccinationRecordElement: {
        prototype: HTMLMedcareVaccinationRecordElement;
        new (): HTMLMedcareVaccinationRecordElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "medcare-medical-records": HTMLMedcareMedicalRecordsElement;
        "medcare-remove-allergy-records": HTMLMedcareRemoveAllergyRecordsElement;
        "medcare-update-lab-results": HTMLMedcareUpdateLabResultsElement;
        "medcare-vaccination-record": HTMLMedcareVaccinationRecordElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MedcareMedicalRecords {
    }
    interface MedcareRemoveAllergyRecords {
    }
    interface MedcareUpdateLabResults {
    }
    interface MedcareVaccinationRecord {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "medcare-medical-records": MedcareMedicalRecords;
        "medcare-remove-allergy-records": MedcareRemoveAllergyRecords;
        "medcare-update-lab-results": MedcareUpdateLabResults;
        "medcare-vaccination-record": MedcareVaccinationRecord;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "medcare-medical-records": LocalJSX.MedcareMedicalRecords & JSXBase.HTMLAttributes<HTMLMedcareMedicalRecordsElement>;
            "medcare-remove-allergy-records": LocalJSX.MedcareRemoveAllergyRecords & JSXBase.HTMLAttributes<HTMLMedcareRemoveAllergyRecordsElement>;
            "medcare-update-lab-results": LocalJSX.MedcareUpdateLabResults & JSXBase.HTMLAttributes<HTMLMedcareUpdateLabResultsElement>;
            "medcare-vaccination-record": LocalJSX.MedcareVaccinationRecord & JSXBase.HTMLAttributes<HTMLMedcareVaccinationRecordElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
